### ISSUE TITLE
Update Organization, Move to R Markdown

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/conjoint-ensembles#24]
I'd like to conform to a standard organization across projects, which includes moving from Overleaf to R Markdown and updating the .gitignore file. I'll need your help with this, @dgmiller.

**Comment by dgmiller** [comment]
@marcdotson What do you mean by standard organization? Do you mean the repository file structure? We can talk about this more offline.

**Comment by marcdotson** [comment]
Yeah, @dgmiller, the file structure plus the README. It'll help me keep track of things better, and help other RAs keep track of things better, across projects.

Let's work on the .gitignore stuff when we meet next week.

**Comment by dgmiller** [comment]
Finished converting all data sets to csv files for cross-language compatibility. I'll be rewriting some of the python functions to read in the csv file data and then transform it to the appropriate dimensions.

**Comment by dgmiller** [comment]
Pending pull request #30

**Comment by dgmiller** [comment]
Pull request #30 merged into master.
