### ISSUE TITLE
Run screening and ANA models

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/conjoint-ensembles#32]
@dgmiller is providing the datasets via Google Drive that we can store in local clones and append to the .gitignore.

@marcdotson will run the screening models and @jeff-dotson will run the ANA models.

**Comment by marcdotson** [comment]
@dgmiller will you email me and @jeff-dotson the link to the drive with the datasets?

**Comment by dgmiller** [comment]
You got the data sets right? Just checking.

**Comment by marcdotson** [comment]
![The+halfling+was+dear+to+thee+i+see+know+that+_092d5a0c0a27dff0bd95fb6eb0b16d67](https://user-images.githubusercontent.com/29615257/57161056-cf83d400-6da7-11e9-86eb-529344582ba8.jpg)

"[I] did, [@dgmiller], I did."

**Comment by marcdotson** [comment]
@jeff-dotson is going to help with ANA. I'm providing the screening model.

**Comment by marcdotson** [comment]
@dgmiller screening model (along with associated C++ functions) [added here](https://github.com/marcdotson/conjoint-ensembles/blob/master/Code/R/conj_hmnl.R).

**Comment by marcdotson** [comment]
Run the models in `05_competing-models.R`.

**Comment by marcdotson** [comment]
Superseded by current work.
