### ISSUE TITLE
Re-run simulations with various randomization strategies

### ISSUE THREAD

**Issue by dgmiller** [marcdotson/conjoint-ensembles#43]
@marcdotson 
Randomize over
+ respondents
+ choice tasks
+ attributes and level
+ alternatives
+ joint randomization

**Comment by marcdotson** [comment]
Save the model output so we can test different measures of fit, including predictive fit for an actual hold-out sample of respondents and not just the hold-out task (though with simulation we might as well investigate both).

**Comment by marcdotson** [comment]
Combining common issues.
