### ISSUE TITLE
Draft "topological coverage" justification

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/conjoint-ensembles#45]
@dgmiller this is something that would be a great contribution uniquely from you. We've talked about it off and on (and maybe part of it is in the current manuscript draft). This should include the math and maybe some visualization, all part of the model specification section.

**Comment by jeff-dotson** [comment]
@dgmiller I'm going to be presenting this paper at Tillburg University in early February and would love to have a working draft. Can you find some time in the next few weeks to draft this section of the paper while Marc and I work on the ensemble comparisons? I think the topological coverage is a cool angle and a critical part of a working draft.

**Comment by dgmiller** [comment]
Acknowledged. I'll see if I can't get it done in the next week or so.

**Comment by marcdotson** [comment]
Subsumed into issue #62.
