### ISSUE TITLE
Modify simulating data and the clever randomization

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/conjoint-ensembles#47]
@jeff-dotson this is yours, working on the `simulation-tuning` branch.

- [x] Allow for pathological heterogeneity across simulated respondents (e.g., not everyone screens on the same attribute levels). This likely requires changes to `clever_randomization()`.

Initial results, for reference:

| Model | LOO | Hit Rate | Hit Prob |
| :--- | :--- | :--- | :--- |
| HMNL | -2732 | 0.566 | 0.446 |
| Ensemble | -13.4 | 0.567 | 0.402 |

**Comment by marcdotson** [comment]
Merged changes from `predictive-fit` so you should be able to run predictive fit on ensemble output.

**Comment by jeff-dotson** [comment]
I'm going to hold off on the simulation of covariates.  This seems to be a "nice-to-have" feature for the paper.  Let's focus on core issues first.

**Comment by marcdotson** [comment]
Merged changes from `predictive-fit` so you should be able to run predictive fit on HMNL output as well (plus some modifications to how predictive fit is computed for the ensembles as well).

**Comment by marcdotson** [comment]
Merged additional changes from `predictive-fit` so you should be able to again go through the whole pipeline and evaluate fit for you heterogeneity changes, @jeff-dotson.

**Comment by marcdotson** [comment]
Changes submitted in PR #58.
