### ISSUE TITLE
Tune running the conjoint ensemble

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/conjoint-ensembles#48]
Mine, working on the `ensemble-tuning` branch.

- [x] Use the posterior from a full model as priors in the ensemble.
- [x] Increase the number of ensemble members/models.

Initial results for a 100-member ensemble using `Beta` for predictive fit:

| Model | LOO | Hit Rate | Hit Prob |
| :--- | :--- | :--- | :--- |
| HMNL | -2732 | 0.566 | 0.446 |
| Ensemble | -13.4 | 0.567 | 0.402 |

**Comment by marcdotson** [comment]
Using the posterior from a full model as priors in the ensemble has no impact on predictive fit as it is currently computed.

**Comment by marcdotson** [comment]
Increasing the number of members in the ensemble, even from just 100 to 200 members, clearly has an impact on predictive fit as it is currently computed (see the updated table above).

**Comment by RogerOverNOut** [comment]
Cool!

**Comment by marcdotson** [comment]
Running ensembles where the number of members/models > 400 appears to run into two memory issues:

1. When running and storing the output of the conjoint ensemble itself. Currently the model fit objects are stored in a list.
2. When extracting ensemble draws for use to produce ensemble weights and model/predictive fit.

The computational time at even 400 members/models has become prohibitive, even when modifying virtual memory allocations and running extracing draws in parallel, making investigating the optimal number of members/models in the ensemble untenable. How can we address this computational bottleneck?

- "Merge" the two steps by fitting and then extracting and storying only the draws needed.
- Reducing the number draws fit/extracted for every member/model.
- Only use upper-level parameter draws for predictive fit, reducing the overall number of draws needed to be extracted.
- Investigate writing a single function for the fit/extract process and parallelizing.

**Comment by marcdotson** [comment]
Results for a 200-member ensemble without `tol_rel_obj = 0.0001` but with `output_samples = 100` and using `Gamma` for predictive fit:

| Model | LOO | Hit Rate | Hit Prob |
| :--- | :--- | :--- | :--- |
| HMNL | -2703 | 0.580 | 0.456 |
| Ensemble | -13.4 | 0.360 | 0.333 |

**Comment by marcdotson** [comment]
By doing fit/extract in one step (only extracting `Gamma` and `log_lik`) we can finally get our first look at the results of a 400-member ensemble. Results for a 400-member ensemble without `tol_rel_obj = 0.0001` but with `output_samples = 100`, using `Gamma` for predictive fit:

| Model | LOO | Hit Rate | Hit Prob |
| :--- | :--- | :--- | :--- |
| HMNL | -2703 | 0.581 | 0.456 |
| Ensemble | -12.8 | 0.360 | 0.333 |

**Comment by RogerOverNOut** [comment]
Yikes....something seems amiss here given that the ensemble is essentially
random guessing!  Is this data up on google drive?  I will take a look this
afternoon/evening.

-Roger

**Comment by marcdotson** [comment]
I've uploaded the set of `ensemble_draws`. I would take a look at what I've done in `ensemble-tuning` with your `predictive_fit_ensemble()` since I may have commented something out that was actually important.

**Comment by RogerOverNOut** [comment]
Hi Guys,

Good news, when I used the sim_ana_400 data, the ensemble fit changes to

Hit rate: .5827
Hit probs: .4176

I'll tidy everything up after dinner and push the updated code.

-Roger

**Comment by marcdotson** [comment]
Hooray! I've updated all the tables above with @RogerOverNOut's modified function. We are good to go.

**Comment by marcdotson** [comment]
Parallelized form of fit/extract/average is so much faster. Testing with just 10 ensembles:

- Using a for loop took 227.986 seconds.
- Using `lapply()` took 193.205 seconds.
- Using `mclapply()` took 74.546 seconds.

Changes submitted with PR #56.
